name: Build Specific Firmware Variant

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Choose firmware variant to build'
        required: true
        default: 'original'
        type: choice
        options:
        - original
        - pc
        - mac
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/west.yml') }}

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: Copy PC config files
        if: github.event.inputs.variant == 'pc'
        run: |
          cp config/my_keyboard_pc.keymap config/eyelash_sofle.keymap
          cp config/my_keyboard_pc.conf config/eyelash_sofle.conf

      - name: Copy Mac config files
        if: github.event.inputs.variant == 'mac'
        run: |
          cp config/my_keyboard_mac.keymap config/eyelash_sofle.keymap  
          cp config/my_keyboard_mac.conf config/eyelash_sofle.conf

      - name: West Build
        run: west build -s zmk/app -d build/central -b nice_nano_v2 -- -DBOARD_ROOT="${GITHUB_WORKSPACE}" -DSHIELD="eyelash_sofle_central_dongle" -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: West Build Left
        run: west build -s zmk/app -d build/left -b nice_nano_v2 -- -DBOARD_ROOT="${GITHUB_WORKSPACE}" -DSHIELD="eyelash_sofle_peripheral_left nice_view" -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: West Build Right  
        run: west build -s zmk/app -d build/right -b nice_nano_v2 -- -DBOARD_ROOT="${GITHUB_WORKSPACE}" -DSHIELD="eyelash_sofle_peripheral_right nice_view" -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: eyelash_sofle_${{ github.event.inputs.variant }}_firmware
          path: |
            build/*/zephyr/zmk.uf2