name: Build ZMK Firmware Variants

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [original, pc, mac]
        include:
          - variant: original
            config: eyelash_sofle
            artifact_suffix: ""
          - variant: pc  
            config: my_keyboard_pc
            artifact_suffix: "_PC"
          - variant: mac
            config: my_keyboard_mac  
            artifact_suffix: "_Mac"
    
    container:
      image: zmkfirmware/zmk-build-arm:stable
    
    name: Build ${{ matrix.variant }} variant
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/west.yml', '**/build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: Copy variant config files
        if: matrix.variant != 'original'
        run: |
          cp config/${{ matrix.config }}.keymap config/eyelash_sofle.keymap
          cp config/${{ matrix.config }}.conf config/eyelash_sofle.conf

      - name: West Build (eyelash_sofle_central_dongle)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD="eyelash_sofle_central_dongle" -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Central Dongle Artifact
        run: cp build/zephyr/zmk.uf2 eyelash_sofle_central_dongle${{ matrix.artifact_suffix }}.uf2

      - name: West Build (eyelash_sofle_peripheral_left)  
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD="eyelash_sofle_peripheral_left nice_view" -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Left Peripheral Artifact
        run: cp build/zephyr/zmk.uf2 eyelash_sofle_peripheral_left${{ matrix.artifact_suffix }}.uf2

      - name: West Build (eyelash_sofle_peripheral_right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD="eyelash_sofle_peripheral_right nice_view" -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Right Peripheral Artifact  
        run: cp build/zephyr/zmk.uf2 eyelash_sofle_peripheral_right${{ matrix.artifact_suffix }}.uf2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eyelash_sofle_firmware${{ matrix.artifact_suffix }}
          path: |
            *.uf2